---
context: "AUEB M.Sc. in Data Science (part-time)"
title: "Data Visualization and Communication - Group homework"
author: "Spiros Politis"
date: "Dec. 2019"
semester: "Fall 2018"
instructor: "D. Karlis"
output:
  bookdown::html_document2:
    theme: cosmo
    toc: false
    toc_float: false
    collapsed: false
    df_print: paged
indent: true
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r code, warnings = FALSE, echo = FALSE, output = TRUE}
source("code/spatial.R")
```

# Spatial plots

```{r mapFlightsOutbound, warnings = FALSE, echo = FALSE, output = TRUE, fig.width = 10, fig.height = 7, fig.align = "center", fig.cap = "\\label{fig:dataFlightsOutbound}Outbound flights from TUL, MKE"}
map.flights.outbound(data.flights.outbout)
```

```{r mapFlightsDelaysSecurity, warnings = FALSE, echo = FALSE, output = TRUE, fig.width = 10, fig.height = 7, fig.align = "center", fig.cap = "\\label{fig:mapFlightsDelaysSecurity}Flight delays due to security reasons for TUL, MKE"}
map.flights.delays.security(data.delays.security.by_destination)
```

